package com.optus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Bandwidth implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String unit;

	public java.lang.Integer tc1;

	public java.lang.Integer tc2;

	public java.lang.Integer tc4;

	public Bandwidth() {
	}

	public java.lang.String getUnit() {
		return this.unit;
	}

	public void setUnit(java.lang.String unit) {
		this.unit = unit;
	}

	public java.lang.Integer getTc1() {
		return this.tc1;
	}

	public void setTc1(java.lang.Integer tc1) {
		this.tc1 = tc1;
	}

	public java.lang.Integer getTc2() {
		return this.tc2;
	}

	public void setTc2(java.lang.Integer tc2) {
		this.tc2 = tc2;
	}

	public java.lang.Integer getTc4() {
		return this.tc4;
	}

	public void setTc4(java.lang.Integer tc4) {
		this.tc4 = tc4;
	}

	public Bandwidth(java.lang.String unit, java.lang.Integer tc1,
			java.lang.Integer tc2, java.lang.Integer tc4) {
		this.unit = unit;
		this.tc1 = tc1;
		this.tc2 = tc2;
		this.tc4 = tc4;
	}
	
    @Override
	public String toString() {
		return "Bandwidth [unit=" + unit + ", tc1=" + tc1 + ", tc2=" + tc2 + ", tc4=" + tc4 + "]";
	}

}