package com.optus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BwChangeException implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String system;
	private java.util.Date createdAt = new java.util.Date();
	private java.lang.String message;

	public BwChangeException() {
	}

	public java.lang.String getSystem() {
		return this.system;
	}

	public void setSystem(java.lang.String system) {
		this.system = system;
	}

	public java.util.Date getCreatedAt() {
		return this.createdAt;
	}

	// public void setCreatedAt(java.util.Date createdAt) {
	// this.createdAt = createdAt;
	// }

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public BwChangeException(java.lang.String system, java.util.Date createdAt,
			java.lang.String message) {
		this.system = system;
		this.createdAt = createdAt;
		this.message = message;
	}

}