package com.optus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CvcBwChangeResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String singleCvcChangeProcessId;
	private java.lang.String cvcId;
	private java.lang.String status;
	private java.util.Date lastUpdatedTime;

	private java.util.List<com.optus.JobCompletion> jobHistory;

	private java.util.List<com.optus.BwChangeException> errors;

	public CvcBwChangeResponse() {
	}

	public java.lang.String getCvcId() {
		return this.cvcId;
	}

	public void setCvcId(java.lang.String cvcId) {
		this.cvcId = cvcId;
	}

	public java.lang.String getSingleCvcChangeProcessId() {
		return this.singleCvcChangeProcessId;
	}

	public void setSingleCvcChangeProcessId(java.lang.String singleCvcChangeProcessId) {
		this.singleCvcChangeProcessId = singleCvcChangeProcessId;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.util.Date getLastUpdatedTime() {
		return this.lastUpdatedTime;
	}

	public void setLastUpdatedTime(java.util.Date lastUpdatedTime) {
		this.lastUpdatedTime = lastUpdatedTime;
	}

	@Override
	public String toString() {
		return JsonUtil.reportInJson(this);
	}

	public java.util.List<com.optus.JobCompletion> getJobHistory() {
		return this.jobHistory;
	}

	public void setJobHistory(java.util.List<com.optus.JobCompletion> jobHistory) {
		this.jobHistory = jobHistory;
	}

	public java.util.List<com.optus.BwChangeException> getErrors() {
		return this.errors;
	}

	public void setErrors(java.util.List<com.optus.BwChangeException> errors) {
		this.errors = errors;
	}

	public CvcBwChangeResponse(java.lang.String singleCvcChangeProcessId, java.lang.String cvcId, java.lang.String status,
			java.util.Date lastUpdatedTime,
			java.util.List<com.optus.JobCompletion> jobHistory,
			java.util.List<com.optus.BwChangeException> errors) {
		this.singleCvcChangeProcessId = singleCvcChangeProcessId;
		this.cvcId = cvcId;
		this.status = status;
		this.lastUpdatedTime = lastUpdatedTime;
		this.jobHistory = jobHistory;
		this.errors = errors;
	}

}