package com.optus;

import java.util.Map;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CvcBwChangeReport implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String referenceNumber;

	Map<String, CvcBwChangeResponse> cvcs;

	private java.lang.String status;

	private java.util.Date startedAt;

	private java.util.Date finishedAt;

	public CvcBwChangeReport() {
	}

	public java.lang.String getReferenceNumber() {
		return this.referenceNumber;
	}

	public void setReferenceNumber(java.lang.String referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	public void setCvcs(Map cvcs) {
		this.cvcs = cvcs;
	}

	public Map<String, CvcBwChangeResponse> getCvcs() {
		return this.cvcs;
	}

	@Override
	public String toString() {
		return JsonUtil.reportInJson(this);
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.util.Date getStartedAt() {
		return this.startedAt;
	}

	public void setStartedAt(java.util.Date startedAt) {
		this.startedAt = startedAt;
	}

	public java.util.Date getFinishedAt() {
		return this.finishedAt;
	}

	public void setFinishedAt(java.util.Date finishedAt) {
		this.finishedAt = finishedAt;
	}

	public CvcBwChangeReport(java.lang.String referenceNumber,
			java.lang.String status, java.util.Date startedAt,
			java.util.Date finishedAt) {
		this.referenceNumber = referenceNumber;
		this.status = status;
		this.startedAt = startedAt;
		this.finishedAt = finishedAt;
	}

}