package com.optus;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CvcBwChangeRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "CVCBWCHANGEREQUEST_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CVCBWCHANGEREQUEST_ID_GENERATOR", sequenceName = "CVCBWCHANGEREQUEST_ID_SEQ")
	private java.lang.Long id;

	private java.util.Date requestDate;

	private java.lang.String requestBy;

	private java.lang.String status;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<com.optus.CvcChange> cvcChangeList;

	private java.lang.String referenceNumber;

	public CvcBwChangeRequest() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(java.util.Date requestDate) {
		this.requestDate = requestDate;
	}

	public java.lang.String getRequestBy() {
		return this.requestBy;
	}

	public void setRequestBy(java.lang.String requestBy) {
		this.requestBy = requestBy;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public CvcBwChangeRequest(java.lang.Long id, java.util.Date requestDate,
			java.lang.String requestBy, java.lang.String referenceNumber,
			java.lang.String status) {
		this.id = id;
		this.requestDate = requestDate;
		this.requestBy = requestBy;
		this.referenceNumber = referenceNumber;
		this.status = status;

	}

	public java.util.List<com.optus.CvcChange> getCvcChangeList() {
		return this.cvcChangeList;
	}

	public void setCvcChangeList(
			java.util.List<com.optus.CvcChange> cvcChangeList) {
		this.cvcChangeList = cvcChangeList;
	}

	public java.lang.String getReferenceNumber() {
		return this.referenceNumber;
	}

	public void setReferenceNumber(java.lang.String referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	public CvcBwChangeRequest(java.lang.Long id, java.util.Date requestDate,
			java.lang.String requestBy, java.lang.String status,
			java.util.List<com.optus.CvcChange> cvcChangeList,
			java.lang.String referenceNumber) {
		this.id = id;
		this.requestDate = requestDate;
		this.requestBy = requestBy;
		this.status = status;
		this.cvcChangeList = cvcChangeList;
		this.referenceNumber = referenceNumber;
	}

}