package com.optus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CvcCancelList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.String> cvcs;

	public CvcCancelList() {
	}

	public java.util.List<java.lang.String> getCvcs() {
		return this.cvcs;
	}

	public void setCvcs(java.util.List<java.lang.String> cvcs) {
		this.cvcs = cvcs;
	}

	public CvcCancelList(java.util.List<java.lang.String> cvcs) {
		this.cvcs = cvcs;
	}

}