package com.optus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class JobCompletion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Integer jobId;
	private java.lang.String system;
	private java.lang.String status;
	private java.util.Date startTime;

	private java.util.Date endTime;

	public JobCompletion() {
	}

	public java.lang.String getSystem() {
		return this.system;
	}

	public void setSystem(java.lang.String system) {
		this.system = system;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.util.Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(java.util.Date startTime) {
		this.startTime = startTime;
	}

	public java.util.Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(java.util.Date endTime) {
		this.endTime = endTime;
	}

	public java.lang.Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(java.lang.Integer jobId) {
		this.jobId = jobId;
	}

	public JobCompletion(java.lang.Integer jobId, java.lang.String system,
			java.lang.String status, java.util.Date startTime,
			java.util.Date endTime) {
		this.jobId = jobId;
		this.system = system;
		this.status = status;
		this.startTime = startTime;
		this.endTime = endTime;
	}

}