package com.optus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NbnPortalOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String orderId;
	private java.lang.String state;
	private java.lang.String failureCode;
	private java.lang.String failureReason;

	public NbnPortalOrder() {
	}

	public java.lang.String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(java.lang.String orderId) {
		this.orderId = orderId;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getFailureCode() {
		return this.failureCode;
	}

	public void setFailureCode(java.lang.String failureCode) {
		this.failureCode = failureCode;
	}

	public java.lang.String getFailureReason() {
		return this.failureReason;
	}

	public void setFailureReason(java.lang.String failureReason) {
		this.failureReason = failureReason;
	}

	public NbnPortalOrder(java.lang.String orderId, java.lang.String state,
			java.lang.String failureCode, java.lang.String failureReason) {
		this.orderId = orderId;
		this.state = state;
		this.failureCode = failureCode;
		this.failureReason = failureReason;
	}

}