package com.optus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NetConfig implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String vendorName;
	private java.lang.String vendorType;
	private java.lang.String deviceIp;
	private Integer vlanId;
	private java.lang.String deviceTid;

	private java.lang.String hostName;

	private java.lang.String neName;

	private String netVlanId;

	private java.lang.String netInterface;

	public NetConfig() {
	}

	public java.lang.String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(java.lang.String vendorName) {
		this.vendorName = vendorName;
	}

	public java.lang.String getVendorType() {
		return this.vendorType;
	}

	public void setVendorType(java.lang.String vendorType) {
		this.vendorType = vendorType;
	}

	public java.lang.String getDeviceIp() {
		return this.deviceIp;
	}

	public void setDeviceIp(java.lang.String deviceIp) {
		this.deviceIp = deviceIp;
	}

	public java.lang.String getDeviceTid() {
		return this.deviceTid;
	}

	public void setDeviceTid(java.lang.String deviceTid) {
		this.deviceTid = deviceTid;
	}

	public java.lang.String getHostName() {
		return this.hostName;
	}

	public void setHostName(java.lang.String hostName) {
		this.hostName = hostName;
	}

	public java.lang.String getNeName() {
		return this.neName;
	}

	public void setNeName(java.lang.String neName) {
		this.neName = neName;
	}

	@Override
	public String toString() {
		return "NetConfig [vendorName=" + vendorName + ", vendorType="
				+ vendorType + ", deviceIp=" + deviceIp + ", vlanId=" + vlanId
				+ ", deviceTid=" + deviceTid + ", hostName=" + hostName
				+ ", neName=" + neName + "]";
	}

	public java.lang.Integer getVlanId() {
		return this.vlanId;
	}

	public void setVlanId(java.lang.Integer vlanId) {
		this.vlanId = vlanId;
	}

	public java.lang.String getNetInterface() {
		return this.netInterface;
	}

	public void setNetInterface(java.lang.String netInterface) {
		this.netInterface = netInterface;
	}

	public java.lang.String getNetVlanId() {
		return this.netVlanId;
	}

	public void setNetVlanId(java.lang.String netVlanId) {
		this.netVlanId = netVlanId;
	}

	public NetConfig(java.lang.String vendorName, java.lang.String vendorType,
			java.lang.String deviceIp, java.lang.Integer vlanId,
			java.lang.String deviceTid, java.lang.String hostName,
			java.lang.String neName, java.lang.String netVlanId,
			java.lang.String netInterface) {
		this.vendorName = vendorName;
		this.vendorType = vendorType;
		this.deviceIp = deviceIp;
		this.vlanId = vlanId;
		this.deviceTid = deviceTid;
		this.hostName = hostName;
		this.neName = neName;
		this.netVlanId = netVlanId;
		this.netInterface = netInterface;
	}

}