package com.optus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TcBwLimit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public java.lang.String tc;
	public java.lang.String resizeAction;
	public java.lang.Integer min;
	public java.lang.Integer max;
	public java.lang.String unit;

	public TcBwLimit() {
	}

	public java.lang.String getTc() {
		return this.tc;
	}

	public void setTc(java.lang.String tc) {
		this.tc = tc;
	}

	public java.lang.String getResizeAction() {
		return this.resizeAction;
	}

	public void setResizeAction(java.lang.String resizeAction) {
		this.resizeAction = resizeAction;
	}

	public java.lang.Integer getMin() {
		return this.min;
	}

	public void setMin(java.lang.Integer min) {
		this.min = min;
	}

	public java.lang.Integer getMax() {
		return this.max;
	}

	public void setMax(java.lang.Integer max) {
		this.max = max;
	}

	public java.lang.String getUnit() {
		return this.unit;
	}

	public void setUnit(java.lang.String unit) {
		this.unit = unit;
	}

	@Override
	public String toString() {
		return "TcBwLimit [tc=" + tc + ", resize action=" + resizeAction
				+ ", unit=" + unit + ", min=" + min + ", max=" + max + "]";
	}

	public TcBwLimit(java.lang.String tc, java.lang.String resizeAction,
			java.lang.Integer min, java.lang.Integer max, java.lang.String unit) {
		this.tc = tc;
		this.resizeAction = resizeAction;
		this.min = min;
		this.max = max;
		this.unit = unit;
	}
}