package com.optus.cvcresize;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Test implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TEST_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "TEST_ID_GENERATOR", sequenceName = "TEST_ID_SEQ")
    private java.lang.Long id;

    public Test() {
    }
    
    public Test(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}